5 CLS
10 RANDOMIZE
15 LET N=INT(RND*100)+1
20 PRINT "EU ACABO DE IMAGINAR UM NUMERO"
25 PRINT "TENTE ADIVINHA-LO (1 a 100)"
30 INPUT G
35 IF G<N THEN PRINT "ESTA BAIXO; TENTE NOVAMENTE": GOTO 30
40 IF G>N THEN PRINT "ESTA ALTO; TENTE NOVAMENTE": GOTO 30
45 IF G=N THEN PRINT "MUITO BEM! O NUMERO ERA "; N

